name: willbee_app
description: "A new Flutter project for WillBee Nursery."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Ø§Ù„Ù…ÙƒØªØ¨Ø§Øª Ø¨ØªØ§Ø¹ØªÙ†Ø§
  http: ^1.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_launcher_icons: ^0.13.1
  package_info_plus: ^4.0.2
  url_launcher: ^6.1.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"   # ðŸ‘ˆ Ø¯Ù‡ Ù…Ø³Ø§Ø± ØµÙˆØ±ØªÙƒ
  min_sdk_android: 21
 